name: Validate Standard Works DB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run normalization check
        run: |
          python scripts/check_normalization.py --db volumes/scripdb/standardworks.db

